### ISSUE TITLE
Allow for the Specification of Either XPath Version 1 or XPath Version 2 When Running Checks

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#15]
The current implementation of `chasten` is hard-coded so that it only works with
XPath 2 expressions. While this is nice because of the fact that it supports the
greatest range of XPath expressions, it is likely going to make the execution of
XPath expressions slower when they would work sufficiently well with the version
1 system instead of the version 2 system.

There are some more details about this issue at:

https://github.com/spookylukey/pyastgrep

One idea would be that `chasten analyze` could accept a command line argument
that would support the specification of whether or not the tool should use XPath
1 or XPath 2 to run all of the expressions associated with the checks.

Alternatively, it might be a good idea to allow the person who writes the
`checks.yml` file to use an extra attribute to specify whether a certain check
should use the XPath version 1 or version 2 parse.

**Comment by gkapfham** [comment]
FIXME: add finley to this

**Comment by KevenDuverglas** [comment]
Myself (@Finley8), @gyamfi01, and I reviewed the `checks.yml` file. As we were trying to understand the differences between XPath 2 expressions and XPath 1 expressions, we found it challenging to decipher the distinction. We're aware that `checks.yml` is essential for the functionality of `chasten`. We have the following questions:

1. How can you determine that XPath 2 is slower than XPath 1?
2. Were specific tests run to see the differences in performance between XPath 1 and XPath 2 expressions?
3. Which resources did @gkapfham use to write the `checks.yml` file? Were there any particular blueprints or online websites referenced?
4. Is there an issue with `chasten`, or is this just a suggestion to improve its usage?
5. What influenced the decision to use XPath 2 over XPath 1 for the `checks.yml` file?

**Comment by Finley8** [comment]
@Finley8 (Me), @gyamfi01, and @KevenDuverglas researched Xpath 1 and 2 expressions. We focused on the relations of syntax and nodes within XPath expressions. We have searched through the `checks.yml` file to determine what must be changed. We could not figure out how to add or change the `checks.yml` file to implement Xpath 1.  We need to have more conversations with the lead developer to figure out how much more time we will need to spend on this issue.

**Comment by Finley8** [comment]
@Finley8 (Me), @gyamfi01, and @KevenDuverglas researched Xpath 1 and 2 expressions. We focused on the relations of syntax and nodes within XPath expressions. We have searched through the `checks.yml` file to determine what must be changed. We could not figure out how to add or change the `checks.yml` file to implement Xpath 1.  We need to have more conversations with the lead developer to figure out how much more time we will need to spend on this issue.

**Comment by VitalJoseph** [comment]
> Myself (@Finley8), @gyamfi01, and I reviewed the `checks.yml` file. As we were trying to understand the differences between XPath 2 expressions and XPath 1 expressions, we found it challenging to decipher the distinction. We're aware that `checks.yml` is essential for the functionality of `chasten`. We have the following questions:
> 
> 1. How can you determine that XPath 2 is slower than XPath 1?
> 2. Were specific tests run to see the differences in performance between XPath 1 and XPath 2 expressions?
> 3. Which resources did @gkapfham use to write the `checks.yml` file? Were there any particular blueprints or online websites referenced?
> 4. Is there an issue with `chasten`, or is this just a suggestion to improve its usage?
> 5. What influenced the decision to use XPath 2 over XPath 1 for the `checks.yml` file?

To answer question 1, XPath 2 introduced a lot of additional features and improvements like more data types, higher order funtions, and more built in-functions. With these new implementations, Xpath 2 is able to write and evaluate more complex expressions that cant be written in XPath 1.  These features may result in a slower runtime for XPath 2 compared to Xpath 1.

**Comment by KevenDuverglas** [comment]
@VitalJoseph, @Finley8, @KevenDuverglas, and @gyamfi01 Did research and tested the xpath1 on chasten and we discovered to the best of our knowledge that the `pyastgrep` tool doesn't have xpath1 embedded in it. Here is more documentation:

- https://github.com/spookylukey/pyastgrep/blob/master/src/pyastgrep/search.py, upon looking at this Python file my group came to the discovery that a new tool might be needed if we were to test xpath1. Not only that but the `main.py` file in chasten would need to be altered significantly, there needs to be a new tool implemented to service xpath1.
- And there is much more to ask regarding this issue and whether it should be closed.

**Comment by simojo** [comment]
For differences between XPath versions: https://stackoverflow.com/questions/51374344/what-are-the-differences-between-versions-of-xpath-1-0-2-0-3-1

**Comment by simojo** [comment]
> @VitalJoseph, @Finley8, @KevenDuverglas, and @gyamfi01 Did research and tested the xpath1 on chasten and we discovered to the best of our knowledge that the `pyastgrep` tool doesn't have xpath1 embedded in it. Here is more documentation:
> 
> * https://github.com/spookylukey/pyastgrep/blob/master/src/pyastgrep/search.py, upon looking at this Python file my group came to the discovery that a new tool might be needed if we were to test xpath1. Not only that but the `main.py` file in chasten would need to be altered significantly, there needs to be a new tool implemented to service xpath1.
> * And there is much more to ask regarding this issue and whether it should be closed.

Just dropping this here for reference: within the file you mentioned, you can specify XPath version [here](https://github.com/spookylukey/pyastgrep/blob/0f4bb3c3e0536f69ab3ec660a15a4994a39ca891/src/pyastgrep/search.py#L66)

**Comment by simojo** [comment]
Is there any kind of feature branch with what's been done so far for this issue? If not, let's make one as soon as we can and we'll start messing with the config schema for starters. @ me when you can.

**Comment by Finley8** [comment]
@simojo @VitalJoseph @KevenDuverglas @gyamfi01 https://github.com/AstuteSource/chasten/tree/Xpath-1-Checks

**Comment by KevenDuverglas** [comment]
While running chasten we came upon an error where you are unable to see now command line interface unless you run `poetry run` first.

**Comment by Finley8** [comment]
![Analyze 1](https://github.com/AstuteSource/chasten/assets/112563950/47616db5-749b-4c32-b782-d53611383e4a)
![Analyze 2](https://github.com/AstuteSource/chasten/assets/112563950/af47e119-a721-4bf5-b4bf-72d3bf74bf8d)
Here is our problem when run. Does anyone have any ideas of how we can go about fixing this?
