### ISSUE TITLE
Create a Wiki or an External Web Site that Provides Detailed Tool Use Documentation

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#21]
While the current README.md file for `chasten` provides a basic overview of the commands
and how they work, it does not include a significant number of examples. This means that it is important to create either a wiki inside of this repository or an external web site, ideally using Material for Mkdocs or Quarto, that will provide additional documentation for the tool!

**Comment by AlishChhetri** [comment]
I would like to tackle this task, but I currently do not have permission to assign myself to the issue.

**Comment by AlishChhetri** [comment]
I created the external site and will continue to maintain and add content to it throughout the semester.

Link: https://chastendocs.netlify.app/
