### ISSUE TITLE
Document the Use of the `log` Sub-Command in the README.md

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#22]
Right now the README.md command does not explain how to the `chasten log` that
starts the syslog server. This documentation will need to explain what is a
syslog server, which it is useful to have a syslog server, and then given an
overview of the kind of output that `chasten`'s syslog server provides.

**Comment by gkapfham** [comment]
Hi @churd01, have you gotten the log feature to work? Please note that you will need to startup the logging server in one terminal window and then run `chasten` so that it sends logging information to that logging server.

It is also worth noting that it is possible to use the run `chasten` and configure it so that it displays logging information in its own terminal when it is running. The documentation that you create should also reflect this feature as well.

Finally, and most importantly, it is worth thinking about whether this documentation is most useful for developers or for people who are going to use the tool. Depending on your audience, where do you think that it is best for the documentation to appear?

**Comment by KellerLiptrap** [comment]
Resolved in https://github.com/AstuteSource/chasten/pull/70
