### ISSUE TITLE
Document the Use of Console Logging Options through the Tool's Command-Line

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#23]
The current version of the README.md file does not explain the various ways in which it is possible to configure either console-based on syslog-based logging. Here is an example of a command-line that turns on and configures logging:

```
chasten analyze diagrams --config /home/gkapfham/working/source/astute-subjects/chasten-configuration --search-path /home/gkapfham/working/source/astute-subjects/subject-forks/diagrams/ --save-directory /home/gkapfham/working/source/astute-subjects/subject-data/diagrams --debug-level ERROR --debug-dest SYSLOG --save
```

The README.md file needs more details about logging and how it works. It should also explain the various logging levels and give examples of the types of logging information that are displayed.

**Comment by KellerLiptrap** [comment]
Solved in https://github.com/AstuteSource/chasten/pull/70

**Comment by gkapfham** [comment]
Based on what @KellerLiptrap wrote in a previous comment, I think that we can close this issue. I am going to close it now! If I have overlooked something, please consider reopening the issue. Thanks!
