### ISSUE TITLE
Add Git Pre-Commit Hooks to Check Commit Messages and Run All Checks

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#29]
While this repository has many checks that are run at the point when you commit to the GitHub repository, it would be ideal if many/most/all of these checks could also be run before a commit takes place. This is possible through the use of Git pre-commit hooks that developers for the project can install after cloning the repository the first! As such, we should add a pre-commit configuration for this repository and run checks on each commit. To complete this task we will need to confirm that the pre-commit hooks work correctly when a commit happens from a text editor, an IDE, and from the command-line.

**Comment by boulais01** [comment]
Made this branch to work in: https://github.com/AstuteSource/chasten/tree/pre-commit
