### ISSUE TITLE
Dump and/or Display XML Files for a Potentially Nested Directory Structure of Python Source Code

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#32]
As described in issue #31, it would be useful to dump the XML representation of
a single specified file on the command-line. With that said, it would also be
great if it was possible to create/display an XML file for all of the Python
files in a directory structure. This would make it possible to save a bunch of
different XML files that could then be browsed while writing XPath expressions
for querying the code base of a Python project.

**Comment by gkapfham** [comment]
FIXME: add mordred

**Comment by boulais01** [comment]
I've added myself, all set there.

**Comment by boulais01** [comment]
This is being worked on as part of Issue #31, in https://github.com/rodriguez03/chasten/tree/mbranch

**Comment by gkapfham** [comment]
Hello @boulais01, can you give a status update on the completion of a PR that will resolve this issue?
