### ISSUE TITLE
Stop Using a Hard Coded Project/App Name During Deployment to Fly or Vercel

### ISSUE THREAD

**Issue by gkapfham** [AstuteSource/chasten#4]
The current implementation of `chasten` has a hard-coded name for the
application/project that is deployed to a hosting platform like Fly or Vercel.

This means that when a person is using `chasten`'s `datasette-publish`
sub-command they will not be able to deploy a datasette.

To solve this problem, this sub-command should offer an new required argument
that is the name of the application/project that should be deployed.

**Comment by hankgref** [comment]
Just assigned this to myself, working on it now
