### ISSUE TITLE
Issue running the tests (pytest)

### ISSUE THREAD

**Issue by hayleepierce** [AstuteSource/chasten#45]
I ran into this issue while trying to remove the pysqlite3 dependency. After removing the dependency, I used the `pytest -x -s -vv -n auto` command to run the tests. Although, it gave me the following error: `'pytest' is not recognized as an internal or external command, operable program or batch file.` I have ran `poetry install`, `poetry lock`, and `poetry update` to confirm that pytest was installed as a dependency.

**Comment by gkapfham** [comment]
Hi! Can you please give a status update on this issue. I have followed the steps that you described here and I was not able to replicate this problem on my development workstation @hayleepierce. Based on the error message that you are reporting it looks like this was either not run in the virtual environment or there was some problem with the installation of dependencies into the virtual environment.

I think that it is critically important that we have some other team members look into this! We need these team members to help:
- Another team member who uses Windows
- At least one team member who uses MacOS and Linux
- Team members who are trying to run the command both with and without the `pysqlite3` dependency

**Comment by hayleepierce** [comment]
The tests are currently working using the `poetry run pytest -x -s -vv -n auto` command. This was run using the version of chasten in the `pysqlite3-removal-test-branch`.
