### ISSUE TITLE
Interact Command crashes when clicking out of Analyze section

### ISSUE THREAD

**Issue by Poiuy7312** [AstuteSource/chasten#79]
**Describe the bug**
The window that appears when running Interact Crashes when going from the Analyze section to any other section on the window

**To Reproduce**

**To Reproduce**
1. run 'chasten interact'
2. Click on analyze
3. Click on any other command

It should not be crashing when switching between commands

**Desktop (please complete the following information):**
 - OS: Windows 11
![image_2023-09-29_093154940](https://github.com/AstuteSource/chasten/assets/112420784/6c3162df-fdfd-4a52-bb20-36e52cee85b2)

**Comment by Bchass** [comment]
Seems to be a issue with others also using trogon: https://github.com/Textualize/trogon/issues/56. Downgrading to an earlier version yields the same results.

**Comment by gkapfham** [comment]
Note: we have a PR that will resolve this issue once PR #109 is merged.
