### ISSUE TITLE
Automate Version Updates For PyPi

### ISSUE THREAD

**Issue by boulais01** [AstuteSource/chasten#80]
The current problem is that version updates to the .toml must be made manually.

Ideally, this can be automated, although it is said this will make the publish.yml file a little more complicated, I expect the tradeoff will be worth it in the long run.

**Comment by boulais01** [comment]
@VitalJoseph @KellerLiptrap Have you made any progress on this? Remember that @MilesF25 and @AidanNeeson have some experience with this.

**Comment by boulais01** [comment]
https://dev.to/iamtekson/publish-package-to-pypi-and-release-new-version-using-github-actions-108k

**Comment by boulais01** [comment]
Please give a progress update on this before 5pm today, as the goal was for this to be done at 2:30pm today.

**Comment by MilesF25** [comment]
I added code for the automation but I'm not sure how to test without trying to push to PyPi. Would it be better to test pushing with this branch or should we merge then test?

**Comment by boulais01** [comment]
That is an excellent question, @MilesF25.  Perhaps we can get some input from @AidanNeeson and @gkapfham on the best course of action here?

**Comment by AidanNeeson** [comment]
@boulais01 or @MilesF25, could we open a pull request for the branch that contains these changes? It would be better to have a discussion there, as I have a few comments and questions from what I looked at. Thanks!
