### ISSUE TITLE
Remove covbadge from CI

### ISSUE THREAD

**Issue by simojo** [AstuteSource/chasten#86]
**Is your feature request related to a problem? Please describe.**
Many builds have been interrupted by the CI step of generating a badge to show code coverage. Issues #82 and #84 both are examples of how this issue has negatively affected our process.

**Describe the solution you'd like**
For now, I propose that we remove the covbadge step form github actions in order to preserve our momentum. We've been losing steam with minute issues such as this; we could reconsider a covbadge at a later time. 

**Additional context**
*Additionally*, a coverage report is logged in the **Actions** tab of our repository each time a build is ran. Although the coverage report does not publish to the repository, it can be viewed for reference.

@AidanNeeson, @laurennevill, @gkapfham, @jnormile, do any of you have any further input on this?

**Comment by AidanNeeson** [comment]
Hi @simojo, I think I agree with this decision. It seems to be blocking a lot of progress that could be made by the team, as a lot of builds that make larger edits to Chasten's source seem to run into this issue. I have looked into it myself and I cannot seem to reason why this would be happening. Unless anyone else has any other insights, I feel this might be the best short term solution to ensure that the team can get some crucial progress made. And especially with the timeline changes that I am sure you all will make here soon, moving the re-addition of coverage badge publishing to a later date seems fine as long as someone on the team is able and willing to put it back and debug any issues that might come along with it.
