### ISSUE TITLE
PIP will not install/upgrade on the Windows OS build

### ISSUE THREAD

**Issue by AlishChhetri** [AstuteSource/chasten#92]
**Describe the bug**

The issue concerns the installation of pip on the Windows OS build. The build requests that we use the command `python.exe -m pip install --upgrade pip` to upgrade the version of pip instead of the command `pip install -U pip`. The commands differ because of how they handle upgrading pip. The standard `pip install -U pip` command upgrades pip using pip itself, which is usually convenient. However, in certain situations where there might be conflicts or permission issues, a more explicit approach is recommended. The second command, `python.exe -m pip install --upgrade pip`, directly calls the Python interpreter to upgrade pip, ensuring a more reliable upgrade process. This method is preferred in controlled environments or when the standard command encounters issues.

**To Reproduce**
1. Go to the latest workflow in github actions
2. Click on the build status in the different OS
3. Scroll down to the 'Install Pip' section of the build

**Expected behavior**

Due to the current command, `pip install -U pip`, returning the following error `Error: Process completed with exit code 1.`, I believe we should try to use the command `python.exe -m pip install --upgrade pip` to upgrade the pip version. After implementing the new version of the command, we should expect this error to resolve itself, if not more testing is required.

**Screenshots**

![Screenshot from 2023-10-17 16-19-13](https://github.com/AstuteSource/chasten/assets/89533288/d9eaa2e4-6fae-4d99-bddf-e424617ff1e2)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Google Chrome]
 - Version [N/A]

**Comment by hayleepierce** [comment]
This issue was fixed with the most recent change.
